environment:
    test: .myshoplinestg.com
    pre: .preview.myshopline.com
    pro: .myshopline.com


handle:
    test: niki02
    pre: niki-us
    pro: niki-us

database:
    host:
    port:
    user:
    password:

header:
    cookie: '_BEAMER_USER_ID_whBStDUm30458=b99b65e5-1186-4c59-933d-f8e9e5f6f984; _BEAMER_FIRST_VISIT_whBStDUm30458=2023-02-01T06:40:35.843Z; _BEAMER_FIRST_VISIT_undefined=2023-02-06T06:09:10.546Z; _BEAMER_DATE_whBStDUm30458=2023-05-27T02:03:45.681Z; r_b_ined=1; lp_url={%22landingPageHtml%22:%22https://niki02.myshoplinestg.com/apps/bundle/gift-box?activitySeq=SL201SAS85957576772371881719%22%2C%22occurredAt%22:1685427364882}; n_u=75b3cbcff0811b3ffa6cf8491dcb5290; localization=US; a_ste=krobHo7p7fCJvjzWRX1BOsY1fh54BIIH77d9PSnguKm01UjUVhSQaMCYXlAAsFoNb8aFMObih5h5l/EAByfhmg==; r_b_in=1; store_id=1678853009947; merchant_id=4211387386; currency_code=USD; currency_code.sig=nEGddW1-E-8oJfI_Pm_5XNzC2sMi1n3aVzZ3v01csyY; lang=en; lang.sig=HPZEXM6qRQA3fl9QF0Gl5KM_KZ7FwUtDpVV9UEUrrek; addressLang=en; addressLang.sig=fZhLaUxh_564Gt_Ygb8agf56cVb1lYYp6NMpk7wfgaM; userSelectLocale=en; userSelectLocale.sig=xaWhkiDLccJKOWtBx98z0KVVx7o_iP0WoEYPBrEqJCw; currency_code_userSetting=USD; currency_code_userSetting.sig=wreMdGqvcOcZfYXi-Fd1QDxl5OWoQm3s2QLyXkCpvxE; s_id=DF605347F05789FB5DB81F9CF4B5D127; s_id.sig=e5c9a4725344e4792916695137510479; t_cart=a8300407c39b47acbca748efbc4fe8d2; t_cart.sig=c46359831f3414d4c01c2fe2d64655cb; a_lang=zh-hans-cn; f_ds_info.sig=43g--oRK-nUba5nngalJl4TShAQ3T2VZjlmw9qXoZZM; store_id.sig=mVmtcHT57eRPrRLpGKh_JympCrG6YhAfWDK8oOUbhd8; merchant_id.sig=JdG9OdjYaypCshQ26ZRHpUNyoOuPv3UW7kt9Ba4A7VU; history_browse_products=16058651670275146639460603,16058651670150156389680603,16059764306419525969710603,16058651672715224938080603,16059720593553862250140603; history_browse_products.sig=oUI4pDS-ON5ecfmfQBAIWHCgK6rlww0beu4mjmYiW3w; JSESSIONID=34F82FF338806F4AC9E84A5BB7743575; f_ds_info=xnA90F0gs63umF/ghOwdanjdSsHAf44KFSpnjUc7l0CnNgeHzfIbqulQrZ39Pa3cYEZKj5kOO+OxU5eNBLt8HQ==; a_osudb_appid=1163336839; a_osudb_subappid=1; ai_kf_language=zh-hans-cn; n_sess={"session_id":"e5f5fb76-93c5-4f24-97f5-87b9f49fff69","created_at":1686983395261,"last_session_id":"09d7e645-327f-4913-959a-0ffe2438141b","session_create_type":102}; _tracking_consent=%7B%22con%22%3A%7B%22GDPR%22%3A%22%22%7D%2C%22v%22%3A%221.0%22%2C%22lim%22%3A%5B%5D%2C%22reg%22%3A%22%22%7D; a_osudb_csrf=#C01#SID0000076BK300hkchAvZrRrTuwJi/+ZcsjulPZHpFxw3+ILuZpMuyvo36jLev8DumHqB2yEqFdG1bJHrNpgvSe31J/cjt/q2tMeHHL3or6/xgggd/6cUxetB/WdgcsOgeMw3fdLd0zjOjFzMcgNk83cl/uZztEm4oakThbNJGtMbbHdVFcrY; a_cstgc=1163336839_1_4211387386_1686989360054girBM6; a_osudb_uid=4211387386; a_osudb_oar=#01#SID0000076BCTTwsL1ffhSOMl1jUwxBkyXiCPLjSNNVWNGp+KhZ5BeU46rzs/X9edf/DpyHPTuucElZMiXciSDTQ/KHTREF281CEyt61HqSVOOCLs1PTXKzofnac2F8rVjAkAjie0/ei2F5aayPwpHYDxStr/hXQ==; a_lce=1687594160247; a_dhch=niki02; _BEAMER_FILTER_BY_URL_whBStDUm30458=false'


filePath:
    discountCodePath: testData/Activity.json
    preCasePath: testData/preCase.json
























