environment:
    test: .myshoplinestg.com
    pre: .preview.myshopline.com
    pro: .myshopline.com


handle:
    test: niki02
    pre: niki-us
    pro: niki-sg

database:
    host:
    port:
    user:
    password:

header:
    cookie: '_BEAMER_USER_ID_vXnSKpuN10685=47d215e2-aefb-4d86-be1e-3c645d117e6a; _BEAMER_FIRST_VISIT_vXnSKpuN10685=2023-04-20T02:58:49.666Z; _BEAMER_DATE_vXnSKpuN10685=2023-05-31T02:39:28.958Z; a_lang=zh-hans-cn; a_ste=krobHo7p7fCJvjzWRX1BOipeEaUzwFwjbfbsxLVP+pApWryZf4xiHtWPTGkB0atyb8aFMObih5h5l/EAByfhmg==; n_u=d7a8986bd77647c2b7a74fe663915040; f_ds_info=xnA90F0gs63umF/ghOwdavNPx/t1SrrOsMjYmyThF8DnSaw+ZHwCHF5VaiHak+9nYEZKj5kOO+OxU5eNBLt8HQ==; store_id=1678861182133; merchant_id=2005188193; currency_code=SDG; currency_code.sig=Eo2cVy5RtXcccU6AWi4fFcuz7a704laqPBGGyyf18rM; localization=SG; lang=en; lang.sig=HPZEXM6qRQA3fl9QF0Gl5KM_KZ7FwUtDpVV9UEUrrek; addressLang=en; addressLang.sig=fZhLaUxh_564Gt_Ygb8agf56cVb1lYYp6NMpk7wfgaM; userSelectLocale=en; userSelectLocale.sig=xaWhkiDLccJKOWtBx98z0KVVx7o_iP0WoEYPBrEqJCw; currency_code_userSetting=SDG; currency_code_userSetting.sig=tqhrJzmnR74kHJE_e7d1PMfEIutz0nQ2AjPvEgbVuLY; lp_url={%22landingPageHtml%22:%22https://niki-sg.myshopline.com/?preview=2&themeId=642f8d220bd5066eadd3a7e1&ignoreRedirect=true&engineType=LAYOUT_ENGINE&templateName=templates%252Findex.html%22%2C%22occurredAt%22:1686281568610}; s_id=3FCD064E023AA1F5B2F196DA4754330A; s_id.sig=89dbf79a6f9c16f3e291dbf1d98c6e24; t_cart=29fa8a0d06e6456e8685a0222e69ce8d; t_cart.sig=5db2194a2a7938b144ff96d5586b3b29; history_browse_products=16058474205174728207673939,16058474203378223921613939; history_browse_products.sig=8OKW3ANiyUjy1JozDbMdBIWTU1pSrs6svyL2f3aNZns; a_osudb_appid=1165600903; a_osudb_subappid=1; r_b_in=1; r_b_ined=1; JSESSIONID=F444424004C30F5534759725AE8A32FB; n_sess={"session_id":"760645a5-9b1f-4c16-8e74-34aa2a11f5b4","created_at":1686744001739,"last_session_id":"28aedddf-92e7-459a-8ee1-364b08da7b63","session_create_type":102}; _BEAMER_BOOSTED_ANNOUNCEMENT_DATE_vXnSKpuN10685=2023-06-15T10:08:19.425Z; _BEAMER_FILTER_BY_URL_vXnSKpuN10685=false; a_cstgc=1165600903_1_2005188193_1687015742767BkhbLV; a_osudb_uid=2005188193; a_osudb_oar=#01#SID0000044BDPP/XMvFFpLpp+Ll0GHniQy+7jjSvXGDx+ImtA82wA9bm9zxSeK1K9XD1gdUdHwg+JaEagJYLolIAdkFVLI+QqZzVQTk2JySuLg3tHBH3YCJn7g1HnAgFyE1oRlLVgKX8csLuCkYMkOgkrMNHuDVQ==; intercom-device-id-ryx6jq53=2604c5e6-eb51-40a2-a84f-0336e7721f7d; a_dhch=niki-sg; _BEAMER_LAST_UPDATE_vXnSKpuN10685=1687015979038; intercom-session-ryx6jq53=OWU4OTE2cGxPQWIranRqTUM0QlBHY1d1NURwVmYrc2Z0R2JrMlR3Z1I1SmptNnBLZTlhYmt1VUsvOHc0cUluSC0tNzZGVUdzc2EvblpJalNrSXdTdGVKUT09--ac01cc4b627a02f64c84bc7fde19dce15ae573e4'


filePath:
    discountCodePath: testData/Activity.json
    preCasePath: testData/preCase.json
























