environment:
    test: .myshoplinestg.com
    pre: .preview.myshopline.com
    pro: .myshopline.com


handle:
    test: niki04
    pre: niki-us
    pro: niki-sg

database:
    host:
    port:
    user:
    password:

header:
    cookie: '_BEAMER_USER_ID_FKUpATyQ57438=ecaadf14-417f-499e-ba21-f3726a72fae3; _BEAMER_FIRST_VISIT_FKUpATyQ57438=2025-02-13T03:24:23.311Z; _hjSessionUser_3760809=eyJpZCI6Ijk0OTgyYjQyLTdhNDktNTcyNy05ZGI2LTk0NmMxMWEzNDI1MyIsImNyZWF0ZWQiOjE3Mzk0MTcwNjA3NTEsImV4aXN0aW5nIjp0cnVlfQ==; _hjDonePolls=982925; _BEAMER_USER_ID_xoATBRYa57439=c8cdce4f-af10-4857-b31f-d5e9e581c650; _BEAMER_FIRST_VISIT_xoATBRYa57439=2025-02-19T07:29:36.964Z; a_lang=zh-hans-cn; a_osudb_appid=1163336839; a_osudb_subappid=1; intercom-device-id-fdjt8drx=8535095a-ad74-42fd-8a57-f5f630270659; a_merchant_behavior_collection=1; sl_sr_session_id=ARdEhzIpFkAHFBKQAAAAAAAAALcDSrBr_ktvj5rY-gFQ0IAsOapqg-RmFgfN73y2yfvL; sl_lr_session_id=ARdEhzIpFkAHFBKQAAAAAAAAADDv8FOcYUX7kcxoqfUfPD_0emf36ULOE6mpVtpNNAd-; _ga=GA1.1.1626892704.1744873230; a_osudb_uid=4211387386; a_osudb_oar=#01#SID0000126BCTtGqBebz51ppiPhZJve9Gy5LTOBHdZ1sNl210GPbKv0GZ5ww0ORCCUh2Ylr73vmbHPU1GgAmE6uZ3iFEseLmMS9m+nuoYkgml+5/jdGK4HWRxa99KsqY7D8pxI56cXoeT8hzsG4uPqhtwqHV3NEA; a_lce=1745478032159; _ga_CVZ36HEL2Z=GS1.1.1744873230.1.0.1744873233.0.0.0; _hjSession_3760809=eyJpZCI6Ijk2N2VkN2QyLTExNDktNDc0MC05ZTBiLWEzOTg4MTYyOGIyOCIsImMiOjE3NDQ4Nzk0MjU3NDgsInMiOjAsInIiOjAsInNiIjowLCJzciI6MCwic2UiOjAsImZzIjowLCJzcCI6MH0=; a_dhch=niki04; sl_sc_session_id=ARdEh5YwFkAHFBKQAAAAAAAAAGO8aGjShU1Pjjwy7Whfpk0bB4xgGh6AEqYbttWFummI; sl_lc_session_id=ARdEh5YwFkAHFBKQAAAAAAAAAKJlunF30k9gr1dS8pB2lJCTZBNCoZbdTV2AOfcOASGK; sl_ls_session_id=ARdEh5YwFkAHFBKQAAAAAAAAABtfkjkCQUGIvp4-fE4bqQRBGxexr2B4uNESi28ms3xO; sl_ss_session_id=ARdEh5YwFkAHFBKQAAAAAAAAACcS-oAVdUgusW7GkV8IrPT-fHonDtrt20xi12LrwrTS; log_session_id=9c6fd4dc-4273-45e1-9b77-4b71c25977fc; r_b_in=1; r_b_ined=1; _BEAMER_FILTER_BY_URL_FKUpATyQ57438=false; _BEAMER_FILTER_BY_URL_FKUpATyQ57438=false; a_ste=yyCTQCkkpt/acXrvGQaLIyztxOWr/Pb9oC57J8X+v9k=; intercom-session-fdjt8drx=TytjaWlXRHZSMVl5ZGNVZlJVc09XSUtoLzBRdERYMS9qZUx0aHJDaHRST2J3S21GNzFYWmk4aVlNSmJqdHoxbDhDcXFqRVRyRVozUXIyZkFsM091Rnc2SmVFTElSRlNVYVhZdUNET0l1Tk09LS1RQXNROUV1SHdJa0UwMFZwTWlFVFJnPT0=--d13e783944f98234e9b9b3bbaff9540e552b3826'


filePath:
    discountCodePath: testData/Activity.json
    preCasePath: testData/preCase.json
























